version: "3.7"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - /var/www/netology/sysadm-homeworks/06-db-02-sql/postgres/vol1:/var/lib/postgresql/data
      - /var/www/netology/sysadm-homeworks/06-db-02-sql/postgres/vol2:/var/lib/postgresql